theme: jekyll-theme-minimal
title: Rushya Puttam
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website/Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryputtam.github.io/" # the base hostname & protocol for your site

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Education"
    url: "/education/"

